BEGIN;
DROP TABLE `ot_logbook_globalsettings`;
DROP TABLE `ot_logbook_usersettings`;
DROP TABLE `ot_logbook_activitydata`;
DROP TABLE `ot_logbook_activity`;
DROP TABLE `ot_logbook_category`;
DROP TABLE `ot_logbook_equipmentdata`;
DROP TABLE `ot_logbook_equipment`;
DROP TABLE `ot_logbook_userdata`;
DROP TABLE `ot_logbook_location`;
DROP TABLE `ot_logbook_subcategory`;
COMMIT;
